Select Year, Count(*) AS FemaleCandidateCount
from election
where cand_sex='F'
group by year;

SELECT ST_NAME, YEAR, COUNT(*) AS TotalCandidates FROM ELECTION
GROUP BY ST_NAME, YEAR;

SELECT ST_NAME, SUM(TOTVOTPOLL) AS TotalVotes FROM ELECTION
WHERE YEAR = 1987 AND PARTYNAME = 'BJP'
GROUP BY ST_NAME;

SELECT ST_NAME, COUNT(*) AS TotalCandidates
FROM ELECTION
WHERE YEAR = 2004
GROUP BY ST_NAME;

SELECT PARTYNAME, SUM(TOTVOTPOLL) AS TotalVotes
FROM ELECTION
WHERE YEAR = 2004 AND ST_NAME = 'UTTAR PRADESH'
GROUP BY PARTYNAME
ORDER BY TotalVotes DESC
LIMIT 5;

